const GET_DOG_IMAGE = {
  INCREASE: "INCREASE",
  DECREASE: "DECREASE",
  REQUEST: "GET_DOG_IMAGE_REQUEST",
  SUCCESS: "GET_DOG_IMAGE_SUCCESS",
  ERROR: "GET_DOG_IMAGE_ERROR",
  CALCULATE: "CALCULATE",
  SECONDNUM: "SECONDNUM",
  ENTER: "ENTER",
};
const LOGIN = {
  LOGIN: "LOGIN",
  UPDATE_TOKEN: "UPDATE_TOKEN",
  SUCCESS: "SUCCESS",
  ERROR: "ERROR",
  LOGOUT: "LOGOUT",
  CHECK_VALIDATE: "CHECK_VALIDATE",
};

const DETAILS = {
  UPDATE: "UPDATE",
  LOAD_IMAGE: "LOAD_IMAGE",
};
export default {
  GET_DOG_IMAGE,
  LOGIN,
  DETAILS,
};
